#!/bin/bash

if [ $# != 1 ]; then
   echo "Usage: clnode status"
   exit 1
else
   if [ "$1" != "status" ]; then
      echo "$1 is not a valid argument."
      exit 1
   fi
fi

cat << EOF

Cluster Nodes ===

--- Node Status ---

Node Name                                             Status
---------                                             ------
vincent                                               Online
theo                                                  Online

EOF
