#!/bin/bash

if [ $# != 1 ]; then
   echo "Usage: clquorum status"
   exit 1
else
   if [ "$1" != "status" ]; then
      echo "$1 is not a valid argument."
      exit 1
   fi
fi

cat << EOF

Cluster Quorum ===

--- Quorum Votes Summary ---

            Needed   Present   Possible
            ------   -------   --------
            2        3         3


--- Quorum Votes by Node ---

Node Name      Present      Possible      Status
---------      -------      --------      ------
vincent        1            1             Online
theo           1            1             Online

--- Quorum Votes by Device ---

Device Name      Present      Possible      Status
-----------      -------      --------      ------
d4               1            1             Online

EOF
